#include <bits/stdc++.h>
using namespace std;

/*

Look-and-Say Sequence

Find the nth term in Look-and-say (Or Count and Say) Sequence. The look-and-say sequence is the sequence of the below integers: 1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, ... 
How is the above sequence generated? 
The nth term is generated by reading (n-1)th term.
The first term is "1"
Second term is "11", generated by reading first term as "One 1" (There is one 1 in previous term)
Third term is "21", generated by reading second term as "Two 1"
Fourth term is "1211", generated by reading third term as "One 2 One 1" and so on

Examples: 
Input: n = 3
Output: 21
Explanation: The 3rd term of the sequence is 21
1st term: 1
2nd term: one 1 -> 11
3rd term: two 1s -> 21
Input: n = 4
Output: 1211
Explanation: The 4th term of the sequence is 1211
1st term: 1
2nd term: one 1 -> 11
3rd term: two 1s -> 21
4th term: one 2 one 1 -> 1211
Input: n = 1
Output: 1
Explanation: The first term of the sequence is 1


1211
11-12-21 -> 111221
*/


/*

Minimum Swaps required to group all 1's together

Given an array of 0's and 1's, we need to write a program to find the minimum number of swaps required to group all 1's present in the array together.
Examples: Input: arr[] = [1, 0, 1, 0, 1]
Output: 1
Explanation: Only 1 swap is required to group all 1's together. Swapping index 1 with 4 will
                        give arr[] = [1, 1, 1, 0, 0]

Input: arr[] = [1, 1, 0, 1, 0, 1, 1]
Output: 2
Explanation: Only 2 swap is required to group all 1's together. Swapping index 0 with 2 and
 1 with 4 will  give arr[] = [0, 0, 1, 1, 1, 1, 1]
Input: arr[] = [0, 0, 0]
Output: -1
Explanation: No 1s are present in the array, so return -1.
*/



//TC: O(n^2) , SC: O(1)

/*

    int n = arr.size();
    int countone = 0;
    
    for (int i = 0; i < n; i++)
    {
        if (arr[i])
            countone++;
    }
    
    if (countone == 0)
        return -1;


    int minswap = INT_MAX;
    for (int i = 0; i < n - countone; i++)
    {
        int one = 0;
        for (int j = i; j < (i + countone); j++)
        {
            if (arr[j])
                one++;
        }
        
        minswap = min(minswap, (countone - one));
    }

    return minswap;
*/
/*

Leaders in an array

Given an array arr[] of size n, the task is to find all the Leaders in the array. An element is a Leader if it is greater than or equal to all the elements to its right side.

Note: The rightmost element is always a leader.


Examples:

Input: arr[] = [16, 17, 4, 3, 5, 2]
Output: [17 5 2]

Explanation: 17 is greater than all the elements to its right i.e., [4, 3, 5, 2], therefore 17 is a leader. 5 is greater than all the elements to its right i.e., [2], therefore 5 is a leader. 2 has no element to its right, therefore 2 is a leader.
Input: arr[] = [1, 2, 3, 4, 5, 2]
Output: [5 2]
Explanation: 5 is greater than all the elements to its right i.e., [2], therefore 5 is a leader. 2 has no element to its right, therefore 2 is a leader.
*/

/*

//TC: O(n)
int main ()
{
    int a []= {4,7,5,3,2};
    int n = sizeof(a)/sizeof(a[0]);
    cout<<a[n-1];
    
    int mx = a[n-1];
    for(int i=n-2; i>=0; i--)
    {
        if(a[i] >= mx)
        {
            cout<<a[i];           
            mx = a[i];
        }
    }
}
*/


/*
//TC: O(n^2)

int main()
{
    int a[] = {16, 17, 4, 3, 5, 2};
    int n = sizeof(a)/sizeof(a[0]);
    
    for(int i=0; i<n; i++)
    {
        int leader = 1;
        
        for(int j=i+1; j<n; j++)
        {
            if(a[j] > a[i])
            {
               leader = 0;
               break;
            }
        }
        
        if(leader == 1)
        {
            cout << a[i] << " ";
        }
    }
}
*/

/*

Third largest element in an array of distinct elements


Given an array of n integers, the task is to find the third largest element. All the elements in the array are distinct integers. 
Examples : 
Input: arr[] = {1, 14, 2, 16, 10, 20}
Output: 14
Explanation: Largest element is 20, second largest element is 16 and third largest element is 14

Input: arr[] = {19, -10, 20, 14, 2, 16, 10}
Output: 16
Explanation: Largest element is 20, second largest element is 19 and third largest element is 16

*/

/*
//TC: O(n)
int main()
{
    int mx1 =INT_MIN;
    int mx2 =INT_MIN;
    int mx3 =INT_MIN;
    
    int a[] ={1,2,3,4,5,6,7};
    
    int n= sizeof(a)/sizeof(a[0]);
    
    for (auto elem: a)
    {
        if(elem > mx1)
        {   mx3= mx2;
            mx2= mx1;
            mx1= elem;
        }
        else if ( elem > mx2 )
        {
            mx3 = mx2;
            mx2 = elem;
        }
        else if ( elem >mx3 )
        {
            mx3  = elem ;
        }
    }
    cout << mx1<<","<<mx2<<","<<mx3;
    
}

*/



/*

Smallest Missing Positive Number:


Given an unsorted array arr[] with both positive and negative elements, find the smallest positive number missing from the array.

Examples:

Input: arr[] = [2, -3, 4, 1, 1, 7]
Output: 3
Explanation: 3 is the smallest positive number missing from the array.

Input: arr[] = [5, 3, 2, 5, 1]
Output: 4
Explanation: 4 is the smallest positive number missing from the array.

Input: arr[] = [-8, 0, -1, -4, -3]
Output: 1 
Explanation: 1 is the smallest positive number missing from the array.


1- Brute force: O(n^2), SC: O(1)
2- Sorting: O(nlogn), SC: O(1)
3- visited array: TC: O(n), SC: O(n)
4- Most optmised: TC: O(n), SC: O(1)


*/

/*
int main()
{
    

    bool visited[n] = {false};
    
     for (int i = 0; i < n; i++) {
         
          if (arr[i] >= 1 && arr[i] <= n)
                vis[arr[i] - 1] = true;
        }
    
     }
     
     for (int i = 0; i < n; i++) {
            if (!vis[i]) {
                return i+1;
            }
        }
    
    return n+1;
}    
    
*/    
    

/*

int main()
{
    int a[] ={2,-3,4,1,1,7};
    int n= sizeof(a)/sizeof(a[0]);

    sort(a,a+n);

    int min = 1;   

    for(int i=0; i<n; i++)
    {
        if(a[i] == min)
        {
            min++;
        }
    }

    cout<<min;
}
*/

/*

int main() {
    int arr[] = {2,3, 4, -1, 1,7};
    int n = sizeof(arr) / sizeof(arr[0]);

    int sm =1;

    for (int num =1; num <= n + 1; num++) {
        bool found = false;

        for (int i =0; i < n; i++) {
            if (arr[i]== num) {
                found =true;
                break;
            }
        }

        if (!found) {
            sm =num;
            break;
        }
    }

    cout << sm;

    return 0;
}

*/
